name: CI - Python 3.8 Beta

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      run : |
        sudo add-apt-repository ppa:deadsnakes/nightly
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends python3.8-dev python3.8-distutils python3.8-setuptools
    - name: Install dependencies
      run: |
        python3.8 -m pip install --upgrade pip
        pip3 install -r dev-requirements.txt
        pip3 install -e .
    - name: Lint with flake8
      run: |
        flake8 phial/ tests/ examples/
    - name: Lint with mypy
      run: |
        mypy phial tests stubs examples --strict-optional --disallow-untyped-defs --disallow-incomplete-defs --disallow-untyped-decorators --no-implicit-optional --disallow-subclassing-any
    - name: Test with pytest
      run: |
        pytest tests -v
